Repository Safecast/safecastapi, pull requests merged in 2018-11, with the labels that each got.

#509 Revert "Sort bgeigie imports by creation date/time"
  app/controllers/bgeigie_imports_controller.rb
  app/models/bgeigie_import.rb
  app/views/layouts/application.html.erb
  spec/controllers/bgeigie_imports_controller_spec.rb
Labels: in progress, review

#504 Open all button
  app/assets/javascripts/application/open_all.js.coffee
  app/helpers/bgeigie_imports_helper.rb
  app/views/bgeigie_imports/index.html.erb
Labels: review

#513 Bump requirements version to address github-flagged vulnerability
  doc/upload_demo/requirements.txt
Labels: review

#514 Update loofah and rack gems to fix security vulnerabilities
  Gemfile.lock
Labels: project:api, review

#515 Migrate to Semaphore 2.0
  .semaphore/semaphore.yml
Labels: review

#518 Docker-containerize Elasticsearch
  Dockerfile
  Dockerfile.elasticsearch
  docker-compose.yml
Labels: WIP, in progress, review, scc-hack2018

#519 Rough query setup from API to elasticsearch
  .env.sample
  Gemfile
  Gemfile.lock
  app/models/ingest_measurement.rb
Labels: in progress, review
