Repository Safecast/safecastapi, pull requests merged in 2018-04, with the labels that each got.

#450 Add measurement_import_id in measurement serialization
  app/models/measurement.rb
Labels: project:api, review

#449 Try to use swagger-blocks to document API response
  Gemfile
  Gemfile.lock
  app/controllers/api_docs_controller.rb
  app/controllers/users_controller.rb
  app/models/user.rb
  config/routes.rb
Labels: project:api, review

#447 Format date/time in ISO format in filter dialog
  app/views/layouts/_datetime_picker.html.erb
Labels: bug, project:api, review

#448 Remove intercom integration
  .env.sample
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  config/initializers/intercom.rb
Labels: in progress, project:api, review

#452 Filter drive id = 28231
  script/dump_clean.sql
  script/ios_query.sql
Labels: review
