Repository Safecast/safecastapi, pull requests merged in 2018-12, with the labels that each got.

#524 Disallow to delete approved bGeigie imports
  app/controllers/bgeigie_imports_controller.rb
  app/views/bgeigie_imports/_show.html.erb
  spec/controllers/bgeigie_imports_controller_spec.rb
Labels: in progress, project:api, review

#523 Support multiple device URNs
  app/models/ingest_measurement.rb
  spec/models/ingest_measurment_spec.rb
Labels: project:api, review, scc-hack2018

#526 Map export script filter updates
  script/dump_clean.sql
  script/ios_query.sql
Labels: review

#517 Approved by column
  app/controllers/bgeigie_imports_controller.rb
  app/models/bgeigie_import.rb
  app/views/bgeigie_imports/index.html.erb
  db/migrate/20181130044638_add_approved_by_to_measurement_imports.rb
  db/structure.sql
Labels: review

#507 Provide import ID after a Md5sum collision
  app/models/measurement_import.rb
  spec/models/measurement_import_spec.rb
Labels: review

#506 Imbrogno exports
  script/imbrogno_daily_export
  script/imbrogno_daily_export.sql
  script/imbrogno_export
  script/imbrogno_export.sql
Labels: in progress, review
