Repository Safecast/safecastapi, pull requests merged in 2019-11, with the labels that each got.

#592 Fix db/structure.sql
  db/structure.sql
Labels: bug

#598 Specify default platform in global config
  .elasticbeanstalk/config.global.yml
Labels: needs review

#581 Update ruby to 2.4.9
  .circleci/config.yml
  .elasticbeanstalk/config.global.yml
  .ruby-version
  Dockerfile
  Dockerfile_completed
  Gemfile
  Gemfile.lock
Labels: project:api

#554 Update rails_admin to 1.4.2
  Gemfile.lock
  config/initializers/rails_admin.rb
  spec/controllers/rails_admin/main_controller_spec.rb
Labels: project:api
