Repository Safecast/safecastapi, pull requests merged in 2020-05, with the labels that each got.

#662 Add elastic APM
  Gemfile
  Gemfile.lock
Labels: needs review

#677 Switch elastic apm activation strategy
  Gemfile
  config/application.rb
Labels: review

#683 Update Rails to 5.2.4.3
  Gemfile
  Gemfile.lock
Labels: in review
