Repository Safecast/safecastapi, pull requests merged in 2021-11, with the labels that each got.

#827 Device story cpm other unit
  app/assets/javascripts/application/device_story_graphs.js
  app/helpers/device_stories_helper.rb
  app/models/ingest_measurement.rb
  app/views/device_stories/show.html.erb
Labels: project:api, device-stories

#831 Update ruby to 2.6.8
  .circleci/Dockerfile
  .circleci/config.yml
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
Labels: project:api

#840 Update Elastic Beanstalk configuration files for Amazon Linux 2
  .circleci/Dockerfile
  .circleci/config.yml
  .circleci/docker-entrypoint.sh
  .ebextensions/50-post-deploy.config
  .ebextensions/logs.config
  .ebextensions/maintenance.config
  .ebextensions/postgresql.config
  .ebextensions/tools.config
  .ebextensions/web.config
  .ebextensions/workers.config
  .ebignore
  .platform/hooks/predeploy/01_add_worker_process_to_procfile.sh
  .platform/nginx/conf.d/blockips.conf
  .platform/nginx/conf.d/maintenance.conf
  .platform/nginx/conf.d/proxy.conf
  .platform/nginx/conf.d/realip.conf
  Dockerfile
  Gemfile.lock
  Procfile
Labels: ops, project:api

#841 Fix for Amazon Linux 2 Platform
  .ebextensions/postgresql.config
  .ebextensions/workers.config
  .platform/hooks/predeploy/02_create_public_system_directory.sh
Labels: ops, project:api

#832 Change /measurements not to issue count query
  app/assets/stylesheets/application/safecast.scss
  app/controllers/measurements_controller.rb
  app/views/measurements/index.html.erb
Labels: project:api
