Repository Safecast/safecastapi, pull requests merged in 2021-12, with the labels that each got.

#833 Prevent highchart.js from getting source map file
  vendor/assets/javascripts/highcharts.js
Labels: project:api

#835 Create configuration file for CodeQL
  .github/codeql/codeql-config.yml
  .github/workflows/codeql-analysis.yml
Labels: project:api

#844 Update elastic-apm from 3.6.0 to 4.4.0
  Gemfile
  Gemfile.lock
  config/application.rb
Labels: project:api, dependencies

#846 Prevent from running multiple same cron jobs
  app/controllers/crons_controller.rb
  spec/controllers/crons_controller_spec.rb
Labels: ops, project:api

#824 add time range selector to device story page
  app/assets/javascripts/device_stories.js
  app/controllers/device_stories_controller.rb
  app/helpers/device_stories_helper.rb
  app/models/ingest_measurement.rb
  app/views/device_stories/show.html.erb
  config/initializers/assets.rb
Labels: project:api, device-stories

#849 Fix code scanning alerts
  app/views/measurements/show.html.erb
Labels: project:api

#852 Fix time range links in device story page
  app/assets/javascripts/device_stories.js
Labels: bug, project:api, device-stories

#834 KMZ download
  Gemfile
  Gemfile.lock
  app/controllers/bgeigie_imports_controller.rb
  app/safecast/actions/bgeigie_imports/kml.rb
  app/views/bgeigie_imports/_head.html.erb
  app/views/bgeigie_imports/bgeigie_logs.kmz.erb
  config/initializers/mime_types.rb
  config/routes.rb
  spec/acceptance/user_downloads_bgeigie_imports_in_kml_spec.rb
  spec/controllers/bgeigie_imports_controller_spec.rb
  spec/safecast/actions/bgeigie_imports/kml_spec.rb
Labels: project:api

#836 Refactor Sign-up and Register forms
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
Labels: project:api

#854 Reset to default locale
  spec/acceptance/user_profile_spec.rb
  spec/models/device_story_comment_spec.rb
Labels: bug, project:api

#837 Hide non-moderator E-mail address when rejecting own bGeigie import
  .elasticbeanstalk/package.sh
  app/controllers/bgeigie_imports_controller.rb
  spec/controllers/bgeigie_imports_controller_spec.rb
Labels: project:api

#838 Add "Global Map" link to device story page
  app/helpers/device_stories_helper.rb
  app/models/device_story.rb
  app/views/device_stories/show.html.erb
  spec/helpers/device_stories_helper_spec.rb
Labels: project:api, device-stories
